DROP TABLE IF EXISTS teachers;

CREATE TABLE teachers (
  Teachid INTEGER PRIMARY KEY,
  priority INTEGER,
  name TEXT NOT NULL,
  faculty TEXT,
  carcolour TEXT,
  course_taught TEXT
  );


          INSERT INTO teachers (Teachid, priority, name, faculty, carcolour, course_taught) VALUES
          (1, 1,'Me Talwork', 'TAS', '/static/carcolor/tascar.png', 'Metal'),
          (2, 1,'Josh Hope', 'TAS', '/static/carcolor/tascar.png', 'Metal'),
          (3, 1,'Josheph Hines', 'TAS', '/static/carcolor/tascar.png', 'Metal'),
          (4, 1,'Matthew Harris', 'TAS', '/static/carcolor/tascar.png', 'Metal'),
          (5, 1,'Robert Simmons', 'TAS', '/static/carcolor/tascar.png', 'Wood'),
          (6, 1,'Alex Hughes', 'TAS', '/static/carcolor/tascar.png', 'Wood'),
          (7, 1,'Reeve Shields', 'TAS', '/static/carcolor/tascar.png', 'Engineering'),
          (8, 1,'Joshua Price', 'TAS', '/static/carcolor/tascar.png', 'Engineering'),
          (9, 1,'Peter Carney', 'TAS', '/static/carcolor/tascar.png', 'Engineering'),   
          (10, 1,'Michael Earley', 'TAS', '/static/carcolor/tascar.png', 'Design and Tech'),
          (11, 1,'Bruce Buckley', 'TAS', '/static/carcolor/tascar.png', 'Design and Tech'),
          (12, 1,'Algor Ithm', 'TAS', '/static/carcolor/tascar.png', 'Software Engineering'),
          (13, 1,'Mark', 'Science', '/static/carcolor/sciencecar.png', 'Physics'),
          (14, 1,'Luke Lea', 'Science', '/static/carcolor/sciencecar.png', 'Physics'),
          (15, 1,'Tanner Mahe', 'Science', '/static/carcolor/sciencecar.png', 'Chemistry'),
          (16, 1,'Py Thone', 'Science', '/static/carcolor/sciencecar.png', 'Chemistry'), 
          (17, 1,'Bio Logist', 'Science', '/static/carcolor/sciencecar.png', 'Biology'),
          (18, 1,'Phy scicst', 'Science', '/static/carcolor/sciencecar.png', 'Physics'),
          (19, 1,'Chemis Ist', 'Science', '/static/carcolor/sciencecar.png', 'Chemistry'),
          (20, 1,'Experi Mante', 'Science', '/static/carcolor/sciencecar.png', 'Chemistry'),
          (21, 1,'Albert Einstein', 'Science', '/static/carcolor/sciencecar.png', 'Biology'),
          (22, 1,'James Maxwell', 'Science', '/static/carcolor/sciencecar.png', 'Biology'),
          (23, 1,'Isacc Newton', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (24, 1,'Kira Lea', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (25, 1,'Pear Tickle', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (26, 1,'Rick Morty', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (27, 1,'Jack Mann', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (28, 1,'Micro Soft', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Standard 2'),
          (29, 1,'Wesley Litt', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Advanced'),
          (30, 1,'Peter Hope', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Advanced'),
          (31, 1,'Jack Price', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Advanced'),
          (32, 1,'Luke Earley', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Extension 1'),
          (33, 1,'Alex Carney', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Extension 1'),
          (34, 1,'Harris Simmons', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Extension 2'),
          (35, 1,'Tanner Shields', 'Mathematics', '/static/carcolor/mathscar.png', 'Mathematics Extension 2'),
          (36, 1,'Mac Buckley', 'History and Languages', '/static/carcolor/halcar.png', 'Japanese Beginners'),
          (37, 1,'Guy Thone', 'History and Languages', '/static/carcolor/halcar.png', 'Chinese Beginners'),
          (38, 1,'Albert Cosmos', 'History and Languages', '/static/carcolor/halcar.png', 'Italian Beginners'),
          (39, 1,'Frank Lea', 'History and Languages', '/static/carcolor/halcar.png', 'Japanese Continuers'),
          (40, 1,'Litt Micro', 'History and Languages', '/static/carcolor/halcar.png', 'Chinese Continuers'),
          (41, 1,'Calcu Lations', 'History and Languages', '/static/carcolor/halcar.png', 'Italian Continuers'),
          (42, 1,'Formu Lae', 'History and Languages', '/static/carcolor/halcar.png', 'Japanese Continuers'),
          (43, 1,'Rick Chemis', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Health And Movement Sciences'),
          (44, 1,'Hughie Hope', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Health And Movement Sciences'),
          (45, 1,'Earley Cola', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Health And Movement Sciences'),
          (46, 1,'Bucky Phi', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Community and Family Studies'),
          (47, 1,'Mack James', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Community and Family Studies'),
          (48, 1,'Walter Welsey', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Community and Family Studies'),
          (49, 1,'Peter Pette', 'PDHPE', '/static/carcolor/pdhpecar.png', 'Sport, Lifestyle and Recreation Studies'),
          (50, 1,'Trig Onomery', 'Human Society and Its Environment (HSIE)', '/static/carcolor/mathscar.png', 'Aboriginal Studies'),
          (51, 1,'Tro Janwar', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Aboriginal Studies'),
          (52, 1,'Renne Saunce', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Ancient History'),
          (53, 1,'Cavel Ary', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Ancient History'),
          (54, 1,'George Wash', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Modern History'),
          (55, 1,'Geo Graphy', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Economics'),
          (56, 1,'His Story', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Legal Studies'),
          (57, 1,'Price Bio', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Geography'),
          (58, 1,'Simon Pear', 'Human Society and Its Environment (HSIE)', '/static/carcolor/hsiecar.png', 'Legal Studies'),
          (59, 1,'Thone Guy', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (60, 1,'Lae Tro', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (61, 1,'Ary Guy', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (62, 1,'Sam Urai', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (63, 1,'Jay May', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (64, 1,'April June', 'Learning Support', '/static/carcolor/lscar.png', 'Learning Support Staff'),
          (65, 1,'June July', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (66, 1,'Augustus Stone', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (67, 1,'Title Wave', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (68, 1,'Ody Sseus', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (69, 1,'Shake Spear', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (70, 1,'Homer', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (71, 1,'Aristo phanes', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (72, 1,'Dant Eisinferno', 'English', '/static/carcolor/englishcar.png', 'English Standard'),
          (73, 1,'Charles Dickens', 'English', '/static/carcolor/englishcar.png', 'English Advanced'),
          (74, 1,'Plato', 'English', '/static/carcolor/englishcar.png', 'English Advanced'),
          (75, 1,'Rea Ding', 'English', '/static/carcolor/englishcar.png', 'English Advanced'),
          (76, 1,'Stephen King', 'English', '/static/carcolor/englishcar.png', 'English Advanced'),
          (77, 1,'Kilo Meters', 'English', '/static/carcolor/englishcar.png', 'English Extension 1'),
          (78, 1,'Ili Ad', 'English', '/static/carcolor/englishcar.png', 'English Extension 1'),
          (79, 1,'Aene Id', 'English', '/static/carcolor/englishcar.png', 'English Extension 2'),
          (80, 1,'Ody Ssey', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (81, 1,'Chain Sawman', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (82, 1,'Ham Ilton', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (83, 1,'Ama Zon', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (84, 1,'May June', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (85, 1,'Urai April', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (86, 1,'Cir Ce', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (87, 1,'Tire Eseas', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (88, 1,'Mecha Tronic', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (89, 1,'Mech Anical', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (90, 1,'Indus Trial', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (91, 1,'Rob Otic', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (92, 1,'Elec Trical', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (93, 1,'Cie Vil', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (94, 1,'Biom Echanical', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (95, 1,'Dae Dalus', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (96, 1,'Archimedes', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (97, 1,'Nikola Tesla', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (98, 1,'Thomas Edison', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (99, 1,'Alexander Bell', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (100, 1,'Steve Jobs', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (101, 1,'Capa Citor', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (102, 1,'Tran Sistor', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (103, 1,'Alan Turing', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (104, 1,'Wilber Wright', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (105, 1,'Orville Wright', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (106, 1,'Tri Cycle', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (107, 1,'Leonardo', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (108, 1,'Da Vinci', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (109, 1,'Broad Way', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (110, 1,'Hades Town', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (111, 1,'Great Gatsby', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (112, 1,'Evan Hansen', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (113, 1,'Heat Hers', 'Student Administration and Support', '/static/carcolor/saascar.png', 'SAAS'),
          (114, 1,'Proform Ance', 'CAPA', '/static/carcolor/capacar.png', 'Dance'),
          (115, 1,'Pain Ting', 'CAPA', '/static/carcolor/capacar.png', 'Creative Arts'),
          (116, 1,'Art Ist', 'CAPA', '/static/carcolor/capacar.png', 'Creative Arts'),
          (117, 1,'Draw Ing', 'CAPA', '/static/carcolor/capacar.png', 'Creative Arts'),
          (118, 1,'Crea Tive', 'CAPA', '/static/carcolor/capacar.png', 'Ceramic'),
          (119, 1,'Cam Era', 'CAPA', '/static/carcolor/capacar.png', 'Photography'),
          (120, 1,'Sing Ing', 'CAPA', '/static/carcolor/capacar.png', 'Music');


          